cart/urls.py
from . import views
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

app_name='cart'

urlpatterns = [
    path('cart-view',views.view_cart,name='view_cart'),
    path('cart-add/<int:id>/',views.add_cart,name='add_cart'),
    path('cart-add/',views.add_cart,name='add_cart'),
    path('cart-delete/<int:id>/',views.delete_cart,name='delete_cart'),
    path('plus-item/',views.item_plus,name='plus_item'),
    path('minus-item/',views.item_minus,name='minus_item'),
    path('clear_cart/',views.clear_cart,name='clear_cart'),
    
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_URL)
   
   
   
    # path('add-to-cart/',views.add_to_cart,name='add-to-cart'),
    # path('cart/',views.cart_view,name='cart'),
    # path('delete-from-cart/',views.delete_item_from_cart,name='delete-from-cart'),
    # path('update-cart/',views.update_cart,name='update-cart'),
   
   

core/urls.py
from django.contrib import admin
from django.urls import path,include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("",include('product.urls')),
    path("user/",include('userauths.urls')),
    path("admin_side/",include('admin_side.urls')),
    path("category_manage/",include('category_manage.urls')),
    path("ad_product/",include('ad_product.urls')),
    path("account/",include('account.urls')),
    path("cart/",include('cart.urls')),
    path("order/",include('order.urls')),
    path("wallet/",include('wallet.urls')),
    path("brands/",include('brands.urls')),
    path("accounts/",include('django.contrib.auth.urls')),


    path('auth/', include('social_django.urls', namespace='social')),

]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)































# """
# URL configuration for core project.

# The `urlpatterns` list routes URLs to views. For more information please see:
#     https://docs.djangoproject.com/en/5.0/topics/http/urls/
# Examples:
# Function views
#     1. Add an import:  from my_app import views
#     2. Add a URL to urlpatterns:  path('', views.home, name='home')
# Class-based views
#     1. Add an import:  from other_app.views import Home
#     2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
# Including another URLconf
#     1. Import the include() function: from django.urls import include, path
#     2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
# """
# from django.contrib import admin
# from django.urls import path,include

# from django.conf import settings
# from django.conf.urls.static import static

# urlpatterns = [
#     path('admin/', admin.site.urls),
#     path("",include('product.urls')),
#     path("user/",include('userauths.urls')),
# ]

# urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
# urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

product/urls.py
from django.urls import path, include 
from product.views import *
from django.conf import settings
from django.conf.urls.static import static

app_name = 'product'

urlpatterns = [
    path('',index, name='index'),
    path('products/',product_list_view, name='product-list'),
    path("products/<int:pid>/<int:cate_id>/", product_detail_view, name="product-detail"),
    path("category/", category_list_view, name="category-list"),
    path("category/<id>/", category_product_list, name="category-product-list"),
    path("brand/", brand_list_view, name="brand-list"),
    path("brand/<id>/", brand_product_list, name="brand-product-list"),
    path("search/", search_view, name="search"),
    path("varnts/<int:pid>/<int:avid>/", varnts, name="varnts"),

    ### sort and filter
    path("add-review/<int:id>/", ajax_add_review, name="add-review"),
    path("filter-product/", filter_product, name="filter-product"),

    ###  wishlist
    path('add-to-wishlist/<int:prid>/<int:cid>/', add_wishlist, name='add_wishlist'),
    path('view-from-wishlist/', view_wishlist, name='wishlist'),
    path('delete-from-wishlist/<int:prid>/', delete_wishlist, name='delete_wishlist'),



]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_URL)

product/forms.py
from django import forms
from .models import ProductReview

class ProductReviewForm(forms.ModelForm):
  review = forms.CharField(widget= forms.Textarea(attrs={"placeholder":"Write review"}))

  class Meta:
    model = ProductReview
    fields = ['review', 'rating']
    labels = {
            'rating': 'How would you rate the product',
        }

product/views.py
from django.http import JsonResponse
from django.shortcuts import render, get_object_or_404, redirect
from ad_product.models import Product, ProductVariant, VariantImage, AttributeValue, Attribute, Brand
from django.views.decorators.cache import cache_control
from category_manage.models import Category
from django.db.models import Q
from .models import ProductReview
from django.db.models import Avg,Sum,Count
from .forms import ProductReviewForm
from django.utils.timezone import now
from datetime import timedelta
from .models import Wishlist
from django.contrib import messages
from order.models import OrderItem
from django.template.loader import render_to_string
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.contrib.auth.decorators import login_required
from account.models import UserProfile




# Create your views here.
@cache_control(no_cache=True, must_revalidate=True, max_age=0,no_store = True)
def index(request):
  

  if request.user.is_superuser:
         return redirect('admin_side:dashboard')
  products = ProductVariant.objects.all()
  for product in products:
    if product.stock <  1:
        product.is_active = False
        product.save()

  try:
    products = ProductVariant.objects.filter(is_active = True, featured = True, soft_delete = False, product__soft_delete=False, stock__gt = 0)
    new = ProductVariant.objects.filter(Q(is_active = True)&Q(soft_delete = False, product__soft_delete=False)).order_by("-updated_at")[:10]
    cat = Category.objects.filter(is_available = True) 
    product_variant_quantities = OrderItem.objects.values('order_product').annotate(total_quantity_sold=Sum('quantity'))
    most_sold_variants = product_variant_quantities.order_by('-total_quantity_sold')
    pop = ProductVariant.objects.filter(soft_delete = False, product__soft_delete=False, id__in=most_sold_variants.values_list('order_product', flat=True))
    brands = Brand.objects.filter(soft_delete = False)

    today = now().date()
    start_of_month = today.replace(day=1)
    end_of_month = start_of_month + timedelta(days=31)

    # Get order items for the current month
    order_items = OrderItem.objects.filter(
        ordered_time__date__gte=start_of_month,
        ordered_time__date__lt=end_of_month
    )

    # Aggregate and annotate the product sales
    best_selling_products = order_items.values(
        'order_product__id',
        'order_product__product__product_name',
        'order_product__sale_price',
        'order_product__max_price',
        'order_product__product__product_catg__category_name',  # Include category name
        'order_product__variantimage__images'  # Include the first variant image
    ).annotate(
        total_quantity_sold=Sum('quantity')
    ).order_by('-total_quantity_sold')[:10]


    context = {
      "products":products,
      "new" : new,
      'category' : cat,
      'pop' : pop,
      'brands' : brands,
      'best': best_selling_products

    }
  except Exception as e:
        print(f'the error is {e}')
  return render(request, 'product/index.html', context)


@cache_control(no_cache=True, must_revalidate=True, max_age=0,no_store = True)
def product_list_view(request):
  if request.user.is_superuser:
         return redirect('admin_side:dashboard')
  products_list = ProductVariant.objects.filter(is_active = True, soft_delete = False, product__soft_delete=False, stock__gt = 0)
  paginator = Paginator(products_list, 9)
  count = ProductVariant.objects.filter(is_active = True, soft_delete = False, product__soft_delete=False).count()
  category = Category.objects.all()
  colors = AttributeValue.objects.filter(is_active=True)
  new = ProductVariant.objects.filter(is_active = True, soft_delete=False,  product__soft_delete=False,).order_by("-updated_at")[:3]
  brands = Brand.objects.filter(soft_delete = False)
  print(f'category={category}')
  
  page = request.GET.get('page')

  try:
      products = paginator.page(page)
  except PageNotAnInteger:
      products = paginator.page(1)
  except EmptyPage:
      products = paginator.page(paginator.num_pages)

  

  context = {
    "products":products,
    "count":count, 
    "category" : category,
    "colors" : colors,
    "new" : new,
    "brands" : brands,
    "has_products": products_list.exists()
    
  }
  return render(request, 'product/product-list.html', context)


def filter_product(request):
    if request.user.is_superuser:
         return redirect('admin_side:dashboard')
    categories = request.GET.getlist('category[]')
    colors = request.GET.getlist('color[]')
    brands = request.GET.getlist('brand[]')
    sort_by = request.GET.get('sort_by', '')
    page = request.GET.get('page', 1)

    products = ProductVariant.objects.filter(is_active=True, soft_delete=False, product__soft_delete=False, stock__gt = 0).distinct()

    if categories:
        products = products.filter(product__product_catg__id__in=categories).distinct()

    if colors:
        products = products.filter(color__id__in=colors).distinct()

    if brands:
        products = products.filter(product__product_brand__id__in=brands).distinct()

    if sort_by == 'price_asc':
        products = products.order_by('sale_price')
    elif sort_by == 'price_desc':
        products = products.order_by('-sale_price')
    elif sort_by == 'name_asc':
        products = products.order_by('product__product_name')
    elif sort_by == 'name_desc':
        products = products.order_by('-product__product_name')
    else:
        products = products.order_by('-id')

    paginator = Paginator(products, 9)  # Paginate with 3 items per page

    try:
        products = paginator.page(page)
    except PageNotAnInteger:
        products = paginator.page(1)
    except EmptyPage:
        products = paginator.page(paginator.num_pages)

    if not products:
        return JsonResponse({'data': '', 'pagination': '<p>No products found.</p>'})

    data = render_to_string('product/async/product-list.html', {'products': products})
    pagination = render_to_string('product/async/pagination.html', {'products': products})
    return JsonResponse({'data': data, 'pagination': pagination})




@cache_control(no_cache=True, must_revalidate=True, max_age=0,no_store = True)
def product_detail_view(request, pid, cate_id):
  if request.user.is_superuser:
         return redirect('admin_side:dashboard')
  user_review_count = 0
  product = ProductVariant.objects.get(id=pid, soft_delete = False)
  # review of a product
  prod = Product.objects.filter(product_catg = cate_id)
  product_colors = AttributeValue.objects.filter(productvariant__product_id=product.product_id, productvariant__soft_delete = False).distinct()
  review = ProductReview.objects.filter(product=product).order_by("-date")
  # average review
  average = ProductReview.objects.filter(product=product).aggregate(rating=Avg('rating'))
  # Product Review Form
  review_form = ProductReviewForm()
  product_ids = [product.id for product in prod]
  prodvariants = ProductVariant.objects.filter(product__id__in=product_ids, soft_delete = False).exclude(id=pid)
  make_review = True

  if request.user.is_authenticated:
     user_review_count = ProductReview.objects.filter(user = request.user, product=product).count()

     if user_review_count > 0:
      make_review = False


     wishlist = Wishlist.objects.filter(user=request.user, wish_item=product).exists()
  else:
     wishlist = False

  context = {
    "make_review" : make_review,
    "p" : product,
    "var" : product_colors,
    "average" : average,
    "rproducts" : prodvariants,
    "review" : review,
    "review_form" : review_form,
    "in_wishlist": wishlist,

  }

  return render(request, 'product/product-detail.html', context)


@login_required(login_url='userauths:sign-in')
def ajax_add_review(request, id):
    if request.user.is_superuser:
         return redirect('admin_side:dashboard')
    product = ProductVariant.objects.get(pk = id)
    user = request.user
    userp = UserProfile.objects.get(user = user)

    rating = request.POST.get('rating')
    print(f'the reivceiwsdjlkfadh    {request.POST.get("review")}')
    review = ProductReview.objects.create(
        user = user,
        product = product,
        review=request.POST.get('review'),
        rating=int(rating),
    )


    return redirect('product:product-detail', product.id, product.product.product_catg.id)



def search_view(request):
  if request.user.is_superuser:
         return redirect('admin_side:dashboard')
  query = request.GET.get('q')

  products = ProductVariant.objects.filter(product__product_name__icontains=query, stock__gt=0, is_active=True).order_by("-created_at")
  count = products.count()

  context = {
    "products" : products,
    "query" : query,
    "count" : count
  }
  return render(request, 'product/search.html', context)


def category_list_view(request):
  if request.user.is_superuser:
         return redirect('admin_side:dashboard')
  categories = Category.objects.all()
  

  context = {
    "categories" : categories,
  }
  return render(request, 'product/category-list.html', context)


def category_product_list(request, id):
  if request.user.is_superuser:
         return redirect('admin_side:dashboard')
  category = Category.objects.get(id=id)
  products = ProductVariant.objects.filter(
    Q(product_status="published") | Q(product__product_catg=category),
    soft_delete=False,  product__soft_delete=False,
)

  context = {
    "category" :   category,
    "products" :   products,

  }
  return render(request, "product/category-product-list.html",context)


def brand_list_view(request):
  if request.user.is_superuser:
         return redirect('admin_side:dashboard')
  brand = Brand.objects.filter(soft_delete = False)
  

  context = {
    "brand" : brand,
  }
  return render(request, 'product/brand_list.html', context)


def brand_product_list(request, id):
  if request.user.is_superuser:
         return redirect('admin_side:dashboard')

templates/product/brand_list.html
{% extends "partials/base.html" %}
{% load static %}

{% block content%}
<head>
    <style>
        .category-img {
            display: block;
            width: 300px; /* Set the desired width */
            height: 250px; /* Set the desired height */
            object-fit: cover; /* Crop the image to fit the specified dimensions */
        }
    </style>
</head>
<main class="main">
  <div class="page-header breadcrumb-wrap">
      <div class="container">
          <div class="breadcrumb">
              <a href="{% url "product:index" %}" rel="nofollow">Home</a>
              <span></span>Category
          </div>
      </div>
  </div>
  <section class="mt-50 mb-50">
      <div class="container custom">
          <div class="row">
              <div class="col-lg-12">
                  <div class="single-header mb-50 text-center">
                      <h1 class="text-brand">Brands</h1>
                      <div class="entry-meta meta-1 font-xs mt-15 mb-15">
                          <span class="post-by">{{brand.count}} Brands</span>
                      </div>
                  </div>
                  <div class="loop-grid pr-30">
                      <div class="row">
                        {% for i in brand %}

                        <div class="col-lg-3">
                            <article class="wow fadeIn animated hover-up mb-30">
                                <div class="post-thumb img-hover-scale">
                                    <a href="{% url "product:brand-product-list" i.id %}">
                                        <img class="border-radius-15 category-img" src="{{ i.brand_img.url }}" alt="">
                                    </a>
                                    
                                </div>
                                <div class="entry-content-2">
                                    <h4 class="post-title mb-15">
                                        <a href="{% url "product:brand-product-list" i.id %}">{{i.brand_name}}</a></h4>
                                    
                                    
                                    <div class="entry-meta meta-1 font-xs color-grey mt-10 pb-10">
                                        <a href="{% url "product:brand-product-list" i.id %}" class="text-brand">Browse <i class="fi-rs-arrow-right"></i></a>
                                    </div>
                                </div>
                            </article>
                        </div>

                        {% endfor %}
                      </div>
                  </div>
                  <!--post-grid-->
                  
              </div>
          </div>
      </div>
  </section>
</main>
   
{% endblock content %}

templates/product/brand_product_list.html
{% extends "partials/base.html" %}
{% load static %}

{% block content%}

<head>
    <style>
        .product-img {
            display: block;
            width: 280px; /* Set the desired width */
            height: 250px; /* Set the desired height */
            object-fit: cover; /* Crop the image to fit the specified dimensions */
        }
    </style>
</head>

<main class="main">
  <div class="page-header breadcrumb-wrap">
      <div class="container">
          <div class="breadcrumb">
              <a href="{% url "product:index" %}" rel="nofollow">Home</a>
              <span></span><a href="{% url "product:category-list" %}">Category</a>
              <span></span>{{category}}
          </div>
      </div>
  </div>
  <section class="mt-50 mb-50">
      <div class="container">
          <div class="row">
              <div class="col-lg-12">
                <div class="shop-product-fillter">
                    <div class="totall-product">
                        <h1 class="text-brand">{{brand}}</h1>
                        <p> We found <strong class="text-brand">{{products.count}}</strong> products for you!</p>
                    </div>
                      
                </div>
                  <div class="row product-grid-3">

                    {% for i in products %}

                    <div class="col-lg-3 col-md-4">
                        <div class="product-cart-wrap mb-30">
                            <div class="product-img-action-wrap">
                                <div class="product-img product-img-zoom">
                                    <a href="{% url "product:product-detail" i.id i.product.product_catg.id  %}">
                                        <img class="default-img product-img" src="{{ i.variantimage_set.first.images.url }}" alt="">
                                        <img class="hover-img product-img" src="{{ i.variantimage_set.first.images.url }}" alt="">
                                    </a>
                                </div>
                                <div class="product-action-1">
                                    <a aria-label="Add To Wishlist" class="action-btn hover-up" href="{% url 'product:add_wishlist' i.id i.product.product_catg.id%}"><i class="fi-rs-heart"></i></a>
                                </div>
                                <div class="product-badges product-badges-position product-badges-mrg">
                                    {% if not i.sale_price == i.max_price %}
                                    <span class="hot">-{{i.get_percentage|floatformat:0}}%</span>
                                    {% endif %}
                                </div>
                            </div>
                            <div class="product-content-wrap">
                                <div class="product-category">
                                    <a href="#">{{i.color}}</a>
                                </div>
                                <h2><a href="{% url "product:product-detail" i.id i.product.product_catg.id  %}">{{i.product}}</a></h2>
                               
                                <div class="product-category">  
                                    <a href="#">{{i.product.product_catg}}</a>
                                </div>
                                <div class="product-price">
                                    <span> Rs.<span id="current-product-price" class="current-product-price-{{i.id}}">{{ i.sale_price }}</span></span>
                                    {% if not i.sale_price == i.max_price %}
                                        <span class="old-price">Rs.{{i.max_price}}</span>
                                    {% endif %}
                                </div>
                                <div class="add-cart">
                                    <div class="product-action-1 show"> 
                                        <input type="hidden" value="1" id="product-quantity" class="product-quantity-{{i.id}}">
                                        <input type="hidden" value="{{i.model_id}}" class="product-pid-{{i.id}}">
                                        <input type="hidden" value="{{ i.variantimage_set.first.images.url }}" class="product-image-{{i.id}}">
                                        <input type="hidden" value="{{i.id}}" class="product-id-{{i.id}}">
                                        <input type="hidden" value="{{i.product}}" class="product-title-{{i.id}}">
                                        <span class="action-btn">
                                            <a href="{% url 'cart:add_cart' id=i.id %}"> <button aria-label="Add To Cart" data-index="{{ i.id }}" id="add-to-cart-btn" class="add add-to-cart-btn hover-up">
                                                
                                                    <i class="fi-rs-shopping-bag-add"></i>
                                                </button>
                                            </a>
                                        </span>

                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>

                    {% endfor %}
                      
                  </div>
              </div>
          </div>
      </div>
  </section>
</main>

{% endblock content%}

templates/product/category-product-list.html
{% extends "partials/base.html" %}
{% load static %}

{% block content%}

<head>
    <style>
        .product-img {
            display: block;
            width: 280px; /* Set the desired width */
            height: 250px; /* Set the desired height */
            object-fit: cover; /* Crop the image to fit the specified dimensions */
        }
    </style>
</head>

<main class="main">
  <div class="page-header breadcrumb-wrap">
      <div class="container">
          <div class="breadcrumb">
              <a href="{% url "product:index" %}" rel="nofollow">Home</a>
              <span></span><a href="{% url "product:category-list" %}">Category</a>
              <span></span>{{category}}
          </div>
      </div>
  </div>
  <section class="mt-50 mb-50">
      <div class="container">
          <div class="row">
              <div class="col-lg-12">
                  <div class="shop-product-fillter">
                      <div class="totall-product">
                          <h1 class="text-brand">{{category}}</h1>
                          <p> We found <strong class="text-brand">{{products.count}}</strong> products for you!</p>
                      </div>
                        
                  </div>
                  <div class="row product-grid-3">

                    {% for i in products %}

                    <div class="col-lg-3 col-md-4">
                        <div class="product-cart-wrap mb-30">
                            <div class="product-img-action-wrap">
                                <div class="product-img product-img-zoom">
                                    <a href="{% url "product:product-detail" i.id i.product.product_catg.id  %}">
                                        <img class="default-img product-img" src="{{ i.variantimage_set.first.images.url }}" alt="">
                                        <img class="hover-img product-img" src="{{ i.variantimage_set.first.images.url }}" alt="">
                                    </a>
                                </div>
                                <div class="product-action-1">
                                    <a aria-label="Add To Wishlist" class="action-btn hover-up" href="{% url 'product:add_wishlist' i.id i.product.product_catg.id%}"><i class="fi-rs-heart"></i></a>
                                </div>
                                <div class="product-badges product-badges-position product-badges-mrg">
                                    {% if not i.sale_price == i.max_price %}
                                    <span class="hot">-{{i.get_percentage|floatformat:0}}%</span>
                                    {% endif %}
                                </div>
                            </div>
                            <div class="product-content-wrap">
                                <div class="product-category">
                                    <a href="#">{{i.color}}</a>
                                </div>
                                <h2><a href="{% url "product:product-detail" i.id i.product.product_catg.id  %}">{{i.product}}</a></h2>
                                <div class="product-category">  
                                    <a href="#">{{i.product.product_catg}}</a>
                                </div>
                                <div class="product-price">
                                    <span> Rs.<span id="current-product-price" class="current-product-price-{{i.id}}">{{ i.sale_price }}</span></span>
                                    {% if not i.sale_price == i.max_price %}
                                        <span class="old-price">Rs.{{i.max_price}}</span>
                                    {% endif %}
                                </div>
                                <div class="add-cart">
                                    <div class="product-action-1 show"> 
                                        <input type="hidden" value="1" id="product-quantity" class="product-quantity-{{i.id}}">
                                        <input type="hidden" value="{{i.model_id}}" class="product-pid-{{i.id}}">
                                        <input type="hidden" value="{{ i.variantimage_set.first.images.url }}" class="product-image-{{i.id}}">
                                        <input type="hidden" value="{{i.id}}" class="product-id-{{i.id}}">
                                        <input type="hidden" value="{{i.product}}" class="product-title-{{i.id}}">
                                        <span class="action-btn">
                                            <a href="{% url 'cart:add_cart' id=i.id %}"> <button aria-label="Add To Cart" data-index="{{ i.id }}" id="add-to-cart-btn" class="add add-to-cart-btn hover-up">
                                                
                                                    <i class="fi-rs-shopping-bag-add"></i>
                                                </button>
                                            </a>
                                        </span>

                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>

                    {% endfor %}
                      
                  </div>
                  <!--pagination-->
                  {% comment %} <div class="pagination-area mt-15 mb-sm-5 mb-lg-0">
                      <nav aria-label="Page navigation example">
                          <ul class="pagination justify-content-start">
                              <li class="page-item active"><a class="page-link" href="#">01</a></li>
                              <li class="page-item"><a class="page-link" href="#">02</a></li>
                              <li class="page-item"><a class="page-link" href="#">03</a></li>
                              <li class="page-item"><a class="page-link dot" href="#">...</a></li>
                              <li class="page-item"><a class="page-link" href="#">16</a></li>
                              <li class="page-item"><a class="page-link" href="#"><i class="fi-rs-angle-double-small-right"></i></a></li>
                          </ul>
                      </nav>
                  </div> {% endcomment %}
              </div>
          </div>
      </div>
  </section>
</main>

{% endblock content%}