account/urls.py
from account import views
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
app_name = 'account'

urlpatterns = [
    path('my-dashboard/', views.my_dashboard, name='my_dashboard'),
    path('add-address/', views.add_address, name='add_address'),
    path('manage-view-address/', views.manage_address, name='manage_address'),
    path('edit_address/<int:id>', views.edit_address, name='edit_address'),
    path('del_address/<int:id>', views.del_address, name='del_address'),
    path('Account_details_edit/', views.account_edit, name='account_edit'),
    # path('change_password/', views.PasswordChangeView.as_view(template_name ='registration/change_password.html'), name='change_password'),  
    path('dashboard/order/<int:id>', views.order_detail, name='order-detail'),  
    path('change_password/', views.CustomPasswordChangeView.as_view(), name='change_password'),







    
]
urlpatterns+= static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cart/urls.py
from . import views
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

app_name='cart'

urlpatterns = [
    path('cart-view',views.view_cart,name='view_cart'),
    path('cart-add/<int:id>/',views.add_cart,name='add_cart'),
    path('cart-add/',views.add_cart,name='add_cart'),
    path('cart-delete/<int:id>/',views.delete_cart,name='delete_cart'),
    path('plus-item/',views.item_plus,name='plus_item'),
    path('minus-item/',views.item_minus,name='minus_item'),
    path('clear_cart/',views.clear_cart,name='clear_cart'),
    
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_URL)
   
   
   
    # path('add-to-cart/',views.add_to_cart,name='add-to-cart'),
    # path('cart/',views.cart_view,name='cart'),
    # path('delete-from-cart/',views.delete_item_from_cart,name='delete-from-cart'),
    # path('update-cart/',views.update_cart,name='update-cart'),
   
   

core/urls.py
from django.contrib import admin
from django.urls import path,include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("",include('product.urls')),
    path("user/",include('userauths.urls')),
    path("admin_side/",include('admin_side.urls')),
    path("category_manage/",include('category_manage.urls')),
    path("ad_product/",include('ad_product.urls')),
    path("account/",include('account.urls')),
    path("cart/",include('cart.urls')),
    path("order/",include('order.urls')),
    path("wallet/",include('wallet.urls')),
    path("brands/",include('brands.urls')),
    path("accounts/",include('django.contrib.auth.urls')),


    path('auth/', include('social_django.urls', namespace='social')),

]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)































# """
# URL configuration for core project.

# The `urlpatterns` list routes URLs to views. For more information please see:
#     https://docs.djangoproject.com/en/5.0/topics/http/urls/
# Examples:
# Function views
#     1. Add an import:  from my_app import views
#     2. Add a URL to urlpatterns:  path('', views.home, name='home')
# Class-based views
#     1. Add an import:  from other_app.views import Home
#     2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
# Including another URLconf
#     1. Import the include() function: from django.urls import include, path
#     2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
# """
# from django.contrib import admin
# from django.urls import path,include

# from django.conf import settings
# from django.conf.urls.static import static

# urlpatterns = [
#     path('admin/', admin.site.urls),
#     path("",include('product.urls')),
#     path("user/",include('userauths.urls')),
# ]

# urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
# urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

order/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'order'

urlpatterns = [
    path('order-manage-view', views.order_view, name="order_view"),
    path('place_order', views.place_order, name="place_order"),
    path('view-order_details', views.order_details, name="order_status"),
    path('download-invoice/<int:order_number>/', views.download_invoice, name='download_invoice'),
    path('view-order_listing/<int:id>', views.order_listing, name="order_listing"),
    path('view_order/<int:id>/', views.user_orders, name='view-orders'),
    path('cancel_order_req/<int:id>/', views.cancel_order_req, name="cancel_order_req"),
    path('view-cancel_order_request/<int:id>/', views.cancel_order, name="cancel_order"),
    path('return_order_req/<int:id>/', views.return_order_req, name="return_order_req"),
    path('view-return_order_request/<int:id>/', views.return_order, name="return_order"),

    path('view-admin_order', views.admin_order_view, name="admin_order_view"),
    path('admin/orders/filter/', views.filter_orders_by_date, name='filter_orders_by_date'),
    path('admin/orders/filter/pdf/', views.filter_orders_pdf, name='filter_orders_pdf'),
    path('admin_order_item_details/<int:id>/', views.admin_order_item_details, name="admin_order_item_details"),
    path('admin_order_item_view/<int:id>/', views.admin_order_item_view, name="admin_order_item_view"),
    path('admin_order_status/', views.admin_order_status, name="admin_order_status"), 
    path('admin_order_status_all/', views.admin_order_status_all, name="admin_order_status_all"), 
    
    path('user_details_views/<int:id>', views.user_details_views, name="user_details_views"),
    path('remove_coupon/', views.remove_coupon, name="remove_coupon"),
   
    path('payment/success',views.payment_success,name='success'),
    path('payment/failed',views.payment_failed,name='failed'),

    


    

]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_URL)

product/urls.py
from django.urls import path, include 
from product.views import *
from django.conf import settings
from django.conf.urls.static import static

app_name = 'product'

urlpatterns = [
    path('',index, name='index'),
    path('products/',product_list_view, name='product-list'),
    path("products/<int:pid>/<int:cate_id>/", product_detail_view, name="product-detail"),
    path("category/", category_list_view, name="category-list"),
    path("category/<id>/", category_product_list, name="category-product-list"),
    path("brand/", brand_list_view, name="brand-list"),
    path("brand/<id>/", brand_product_list, name="brand-product-list"),
    path("search/", search_view, name="search"),
    path("varnts/<int:pid>/<int:avid>/", varnts, name="varnts"),

    ### sort and filter
    path("add-review/<int:id>/", ajax_add_review, name="add-review"),
    path("filter-product/", filter_product, name="filter-product"),

    ###  wishlist
    path('add-to-wishlist/<int:prid>/<int:cid>/', add_wishlist, name='add_wishlist'),
    path('view-from-wishlist/', view_wishlist, name='wishlist'),
    path('delete-from-wishlist/<int:prid>/', delete_wishlist, name='delete_wishlist'),



]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_URL)

wallet/urls.py
from django.urls import path
from wallet import views

app_name = 'wallet'


urlpatterns = [
    
    path('wallet-view', views.wallet_view, name='wallet_view'),
    # path('get_refferal_code', views.get_refferal_code, name='get_refferal_code'),



    


]

wallet/models.py
import uuid
from django.db import models
from order.models import OrderItem
from order.models import Payment
from shortuuidfield import ShortUUIDField
from product.models import User

# Create your models here.
class EasyPay(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    balance = models.DecimalField(max_digits=15, decimal_places=2, null=True, blank=True, default=0.0)
    updated_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.user.username 


class Wallet(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    payment = models.ForeignKey(Payment, on_delete=models.CASCADE, blank=True, null=True)
    order_id = models.CharField(max_length=250, blank=True, null=True)
    order_item = models.ForeignKey(OrderItem, on_delete=models.CASCADE, null=True, blank=True)
    is_debit = models.BooleanField(default=False)
    easypay = models.ForeignKey(EasyPay, on_delete=models.CASCADE, blank=True, null=True)
    amount = models.DecimalField(max_digits=15, decimal_places=2, null=True, blank=True,) 
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.user.username 


class Referral(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    referral = models.CharField( null=True, blank=True, unique= False)
    referral_self = models.CharField(max_length=8, unique=True, null=True, blank=True)
  
    def __str__(self):
        return self.referral_self

wallet/views.py
from django.shortcuts import  get_object_or_404, render, redirect
from wallet.models import Wallet, EasyPay, Referral
from django.db.models import Q
from django.contrib import messages
import shortuuid
from django.contrib.auth.decorators import login_required
from django.core.exceptions import ObjectDoesNotExist

# Create your views here.





@login_required(login_url='userauths:sign-in')
def wallet_view(request):
    if request.user.is_superuser:
         return redirect('admin_side:dashboard')
    try:
        easy = EasyPay.objects.get(user=request.user)
        wallet = Wallet.objects.filter(user=request.user, easypay=easy).order_by('-created_at')
    except ObjectDoesNotExist:
        easy = None
        wallet = None
    context = {
        'wallet': wallet,
        'easy':easy,
    }
    return render(request, 'user/dashboard/wallet.html', context)



def credit(amount, order_item, user):
    print('hi')
    try:
        amount = amount
        order_item = order_item
        easy, check = EasyPay.objects.get_or_create(user = user)
        print('in the has attri checking')
        Wallet.objects.get_or_create(
            user = user,
            easypay = easy,
            payment = order_item.payment_details,
            order_id = order_item.order.order_number,
            order_item = order_item,
            amount = amount,
            is_debit = False,
        )
        easy.balance +=amount
        easy.save()

    except Exception as e:
        print(f'the error is that which is {e}')


@login_required(login_url='userauths:sign-in')
def easypay(total, order, user):
    easy = get_object_or_404(EasyPay, user=user)
    if easy.balance < total:
        return False  # Not enough balance

    easy.balance -= total
    easy.save()

    Wallet.objects.get_or_create(
        user=user,
        easypay=easy,
        payment=order.payment_details,
        order_id=order.order_number,
        amount=total,
        is_debit=True,
    )
    return True


            

        

templates/user/dashboard/edit_account.html
{% extends "partials/base.html" %} 
{% block title %}ACCOUNT EDIT{% endblock title %} 
{%block content %}
{% load static %} 
    


    <style>
        #preview-image {
            max-width: 100%;
            height: auto;
        }

        .cropper-container {
            max-width: 100%;
            height: auto;
        }
        .not-visible {
            display: none;
        }
        body {
            background-color: #f9f9fa
        }
        
        .padding {
            padding: 3rem !important
        }
        
        .user-card-full {
            overflow: hidden;
        }
        
        .card {
            border-radius: 5px;
            -webkit-box-shadow: 0 1px 20px 0 rgba(69,90,100,0.08);
            box-shadow: 0 1px 20px 0 rgba(69,90,100,0.08);
            border: none;
            margin-bottom: 30px;
        }
        
        .m-r-0 {
            margin-right: 0px;
        }
        
        .m-l-0 {
            margin-left: 0px;
        }
        
        .user-card-full .user-profile {
            border-radius: 5px 0 0 5px;
        }
        
        .bg-c-lite-green {
                background: -webkit-gradient(linear, left top, right top, from(#f29263), to(#ee5a6f));
            background: linear-gradient(to right, #ee5a6f, #f29263);
        }
        
        .user-profile {
            padding: 20px 0;
        }
        
        .card-block {
            padding: 1.25rem;
        }
        
        .m-b-25 {
            margin-bottom: 25px;
        }
        
        .img-radius {
            border-radius: 5px;
        }
        
        
         
        h6 {
            font-size: 14px;
        }
        
        .card .card-block p {
            line-height: 25px;
        }
        
        @media only screen and (min-width: 1400px){
        p {
            font-size: 14px;
        }
        }
        
        .card-block {
            padding: 1.25rem;
        }
        
        .b-b-default {
            border-bottom: 1px solid #e0e0e0;
        }
        
        .m-b-20 {
            margin-bottom: 20px;
        }
        
        .p-b-5 {
            padding-bottom: 5px !important;
        }
        
        .card .card-block p {
            line-height: 25px;
        }
        
        .m-b-10 {
            margin-bottom: 10px;
        }
        
        .text-muted {
            color: #919aa3 !important;
        }
        
        .b-b-default {
            border-bottom: 1px solid #e0e0e0;
        }
        
        .f-w-600 {
            font-weight: 600;
        }
        
        .m-b-20 {
            margin-bottom: 20px;
        }
        
        .m-t-40 {
            margin-top: 20px;
        }
        
        .p-b-5 {
            padding-bottom: 5px !important;
        }
        
        .m-b-10 {
            margin-bottom: 10px;
        }
        
        .m-t-40 {
            margin-top: 20px;
        }
        
        .user-card-full .social-link li {
            display: inline-block;
        }
        
        .user-card-full .social-link li a {
            font-size: 20px;
            margin: 0 10px 0 0;
            -webkit-transition: all 0.3s ease-in-out;
            transition: all 0.3s ease-in-out;
        }
        
        
        
      
    </style>
</head>
<body>
    
    <div class="page-header breadcrumb-wrap">
        <div class="container">
            <div class="breadcrumb">
                <a href="{% url "product:index" %}" rel="nofollow">Home</a>
                <span></span> 
                <a href="{% url "account:my_dashboard" %}" rel="nofollow">My Account</a>
                <span></span>Address
            </div>
        </div>
      </div>

    <div class="page-content page-container" id="page-content">
        <div class="padding">
            <div class="row container d-flex justify-content-center">
    <div class="col-xl-6 col-md-12">
        <div class="card user-card-full">
            <div class="row m-l-0 m-r-0">
                <div class="col-sm-4 bg-c-lite-green user-profile">
                    <div class="card-block text-center text-white">
                        {% if myuser.profile_pic %}
                        <div class="m-b-25">
                            <img width="120px"  src="{{myuser.profile_pic.url}}" class="img-radius" alt="User-Profile-Image">
                        </div>
                        {% else %}
                        <div class="m-b-25">
                            <img src="https://img.icons8.com/bubbles/100/000000/user.png" class="img-radius" alt="User-Profile-Image">
                        </div>
                        {% endif %}
                       

                        {% if myuser %}
                        <h6 class="f-w-600">{{myuser.full_name}}</h6>
                        <p>{{request.user}}</p>
                        {% else %}
                        <h6 class="f-w-600">Not Set Yet</h6>
                        <p>{{request.user}}</p>
                        {% endif %}
                        <i class=" mdi mdi-square-edit-outline feather icon-edit m-t-10 f-16"></i>

                    </div>
                </div>
                <div class="col-sm-8">
                    <div class="card-block">
                        <h6 class="m-b-20 p-b-5 b-b-default f-w-600">Information</h6>
                        {% if myuser %}
                        <div class="row">
                            <div class="col-sm-6">
                                <p class="m-b-10 f-w-600">Email</p>
                                <h6 class="text-muted f-w-400">{{request.user.email}}</h6>
                            </div>
                            {% comment %} <div class="col-sm-6">
                                <p class="m-b-10 f-w-600">Phone</p>
                                <h6 class="text-muted f-w-400">{{myuser.phone_number}}</h6>
                            </div> {% endcomment %}
                        </div>
                        <h6 class="m-b-20 m-t-40 p-b-5 b-b-default f-w-600"></h6>
                        <div class="row">
                            {% comment %} <div class="col-sm-6">
                                <p class="m-b-10 f-w-600">DOB</p>
                                <h6 class="text-muted f-w-400">{{myuser.DOB}}</h6>
                            </div> {% endcomment %}
                            <div class="col-sm-6">
                                <p class="m-b-10 f-w-600">Nationality</p>
                                <h6 class="text-muted f-w-400">{{myuser.nationality}}</h6>
                            </div>
                        </div>
                        {% else %}
                        <div class="row">
                            <div class="col-sm-6">
                                <p class="m-b-10 f-w-600">Email</p>
                                <h6 class="text-muted f-w-400">{{request.user.email}}</h6>
                            </div>
                            {% comment %} <div class="col-sm-6">
                                <p class="m-b-10 f-w-600">Phone</p>
                                <h6 class="text-muted f-w-400">None</h6>
                            </div> {% endcomment %}
                        </div>
                        <h6 class="m-b-20 m-t-40 p-b-5 b-b-default f-w-600"></h6>
                        <div class="row">
                            {% comment %} <div class="col-sm-6">
                                <p class="m-b-10 f-w-600">DOB</p>
                                <h6 class="text-muted f-w-400">Not Set</h6>
                            </div> {% endcomment %}
                            <div class="col-sm-6">
                                <p class="m-b-10 f-w-600">Nationality</p>
                                <h6 class="text-muted f-w-400">Not Set</h6>
                            </div>
                        </div>
                        {% endif %}
                            <div class="col-12" style="margin-top:20px; margin-left:40px">
                                <a href="{% url "account:change_password" %}"><button type="submit" class="btn btn-fill-out submit"  value="Submit">Change Password</button></a>
                            </div>
                        <ul class="social-link list-unstyled m-t-40 m-b-10">
                            <li><a href="#!" data-toggle="tooltip" data-placement="bottom" title="" data-original-title="facebook" data-abc="true"><i class="mdi mdi-facebook feather icon-facebook facebook" aria-hidden="true"></i></a></li>
                            <li><a href="#!" data-toggle="tooltip" data-placement="bottom" title="" data-original-title="twitter" data-abc="true"><i class="mdi mdi-twitter feather icon-twitter twitter" aria-hidden="true"></i></a></li>
                            <li><a href="#!" data-toggle="tooltip" data-placement="bottom" title="" data-original-title="instagram" data-abc="true"><i class="mdi mdi-instagram feather icon-instagram instagram" aria-hidden="true"></i></a></li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
        </div>
        </div>
    </div>


    <div class="card-body">
        <form method="post"  action='{% url "account:account_edit" %}' enctype="multipart/form-data" >
            {% csrf_token %}
            <div class="row">
                <div class="form-group col-md-12">
                    <label>Full Name <span class="required"></span></label>
                    <input required value="{{myuser.full_name}}" class="form-control square" name="name" type="text">
                </div>
                <div class="form-group col-md-12">
                    <label>Username<span class="required"></span></label>
                    <input value="{{request.user}}" required class="form-control square" name="dname" type="text" readonly>
                </div>
                <div class="form-group col-md-12">
                    <label>Email Address <span class="required"></span></label>
                    <input required value="{{request.user.email}}" class="form-control square" name="email" type="email" readonly>
                </div>
                {% comment %} <div class="form-group col-md-12">
                    <label>Phone number<span class="required"></span></label>
                    <input required readonly value="{{request.user.phone_number}}" class="form-control square" name="phnumber" type="text">
                </div> {% endcomment %}
                <div class="form-group col-md-12">
                    <label>profile image<span class="required"></span></label>
                    <input   class="form-control square" name="Profile_img" type="file">
                </div>
                
                <div class="form-group col-md-12">
                    <label>Nationality<span class="required"></span></label>
                    <input  value="{{myuser.nationality}}"  class="form-control square" name="nationality" type="text" required>
                </div>
                {% comment %} {% if myuser.DOB %}
                <div class="form-group col-md-12">
                    <label>Date OF Birth<span class="required"></span></label>
                    <input required value="{{myuser.DOB}}"  class="form-control square" name="DOB" type="text" readonly>
                </div>
                {% else %}
                <div class="form-group col-md-12">
                    <label>Date OF Birth<span class="required"></span></label>
                    <input required value="{{myuser.DOB}}"  class="form-control square" name="DOB" type="date" >
                </div>
                {% endif %} {% endcomment %}
                <div class="col-md-12">
                    <button type="submit" class="btn btn-fill-out submit" name="submit" value="Submit">Save</button>
                </div>
            </div>
        </form>
    </div>
    
{% endblock content %} 

templates/user/dashboard/manage_address.html
{% extends "partials/base.html" %} 
{% block title %}MY ADDRESS MANAGEMENT{% endblock title %} 

{%block content %}
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
<style>
  #address{
    margin-top:20px;
  }
  #address_2{
    margin-top:20px;
  }
  #address_3{
    margin-top:20px;
  }
  #address_4{
    margin-top:20px;
  }
  #address_5{
    margin-top:20px;
  }
</style>
<br>
<div class="page-header breadcrumb-wrap">
  <div class="container">
      <div class="breadcrumb">
          <a href="{% url "product:index" %}" rel="nofollow">Home</a>
          <span></span> 
          <a href="{% url "account:my_dashboard" %}" rel="nofollow">My Account</a>
          <span></span>Address
      </div>
  </div>
</div>


{% comment %} the default billing and shipping address {% endcomment %}

<div class="container" >
  <div class="row">
    <div id='address_3' class="col-lg-5">
      {% if default_shipping %}
      
      {% else %}
          <p>THERE IS NO DEFAULT SHIPPING ADDRESS</p>
      {% endif %}
  </div>
  
  <div  id='address_4' class="col-lg-5">
      {% if default_billing %}
      {% else %}
          <p>THERE IS NO DEFAULT BILLING ADDRESS</p>
      {% endif %}
  </div>
    
    {% for d_ship in default_shipping %}
    {% if 'd_ship.FullAddress' %}
      <div id='address' class="col-lg-5">
        <div class="card">
            <div class="card-header">
                <h5 class="mb-0">Default Shipping Address</h5>
            </div>
            <div class="card-body">
                <address>{{d_ship.name}} <br> {{d_ship.FullAddress}}<br>{{d_ship.pincode}}</address>
                <p>Phone: {{d_ship.phone_number}}</p>
                <a href="{% url "account:edit_address" id=d_ship.id %}" class="btn-small">Edit</a>
                <a style="margin-left:20px" href="{% url "account:del_address" id=d_ship.id %}" class="btn-small text-danger">Delete</a>

            </div>
        </div>
      </div>
      {% else %}
      <div id='address' class="col-lg-5">
        <div class="card">
            <div class="card-header">
                <h5 class="mb-0">Default Shipping Address</h5>
            </div>
            <div class="card-body">
              <address>No default shipping address have been created so far<br> <br></address>
              <p>Phone: None </p>
          </div>
        </div>
      </div>
      {% endif %}
      {% endfor %}


      
      {% for d_bill in default_billing %}
      {% if 'd_bill.FullAddress' %}
      <div id='address' class="col-lg-5">
        <div class="card">
            <div class="card-header">
                <h5 class="mb-0">Default Billing Address</h5>
            </div>
            <div class="card-body">
                <address>{{d_bill.name}} <br> {{d_bill.FullAddress}}<br>{{d_bill.pincode}}</address>
                <p>Phone: {{d_bill.phone_number}}</p>
                <a href="{% url "account:edit_address" id=d_bill.id %}" class="btn-small">Edit</a>
                <a style="margin-left:20px" href="{% url "account:del_address" id=d_bill.id %}" class="btn-small text-danger">Delete</a>

            </div>
        </div>
      </div>
      {% else %}
      <div id='address' class="col-lg-5">
        <div class="card">
            <div class="card-header">
                <h5 class="mb-0">Default Shipping Address</h5>
            </div>
            <div class="card-body">
              <address>No default shipping address have been created so far<br> <br></address>
              <p>Phone: None </p>
          </div>
        </div>
      </div>
      {% endif %}
      {% endfor %}
  </div>
</div>


{% comment %} the normal shipping and billing address {% endcomment %}

<div class="container" >
  <div class="row">
    {% for ship in shipping_address %}
      <div id='address' class="col-lg-5">
        <div class="card">
            <div class="card-header">
                <h5 class="mb-0">Shipping Address</h5>
            </div>
            {% if 'ship.FullAddress' %}
            <div class="card-body">
                <address>{{ship.name}} <br> {{ship.FullAddress}}<br>{{ship.pincode}}</address>
                <p>Phone: {{ship.phone_number}}</p>
                <a href="{% url "account:edit_address" id=ship.id %}"  class="btn-small">Edit</a>
                <a style="margin-left:20px" href="{% url "account:del_address" id=ship.id %}" class="btn-small text-danger">Delete</a>

            </div>
            {% else %}
            <div class="card-body">
                <address>No Billing address have been created so far<br> <br></address>
                <p>Phone: None </p>
            </div>
            {% endif %}
        </div>
      </div>
      {% endfor %}
      {% for bill in billing_address %}
      <div id='address_2' class="col-lg-5">
        <div class="card">
            <div class="card-header">
                <h5 class="mb-0">Billing Address</h5>
            </div>
            {% if 'bill.FullAddress' %}
            <div class="card-body">
                <address>{{bill.name}} <br> {{bill.FullAddress}}<br>{{bill.pincode}}</address>
                <p>Phone: {{bill.phone_number}}</p>
                <a href="{% url "account:edit_address" id=bill.id %}" class="btn-small">Edit</a>
                <a style="margin-left:20px" href="{% url "account:del_address" id=bill.id %}" class="btn-small text-danger">Delete</a>

            </div>
            {% else %}
            <div class="card-body">
                <address>No Billing address have been created so far<br> <br></address>
                <p>Phone: None </p>
            </div>
            {% endif %}
        </div>
      </div>
      {% endfor %}
  </div>


{% comment %} all address {% endcomment %}
    <div class="col-lg-5">
      {% if all_address %}
      {% else %}
          <p>THERE IS NO OTHER ADDRESS</p>
      {% endif %}
    </div>
  
      {% for all in all_address %}
      <div id='address_5' class="col-lg-5">
        <div class="card">
            <div class="card-header">
                <h5 class="mb-0">Address</h5>
            </div>
            <div class="card-body">
                <address>{{all.name}} <br> {{all.FullAddress}}<br>{{all.pincode}}</address>
                <p>Phone: {{all.phone_number}}</p>
                <a href="{% url "account:edit_address" id=all.id %}" class="btn-small">Edit</a>
                <a style="margin-left:20px" href="{% url "account:del_address" id=all.id %}" class="btn-small text-danger">Delete</a>

            </div>
        </div>
      </div>
      {% endfor %}
    </div>
{% endblock content %}x