cart/urls.py
from . import views
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

app_name='cart'

urlpatterns = [
    path('cart-view',views.view_cart,name='view_cart'),
    path('cart-add/<int:id>/',views.add_cart,name='add_cart'),
    path('cart-add/',views.add_cart,name='add_cart'),
    path('cart-delete/<int:id>/',views.delete_cart,name='delete_cart'),
    path('plus-item/',views.item_plus,name='plus_item'),
    path('minus-item/',views.item_minus,name='minus_item'),
    path('clear_cart/',views.clear_cart,name='clear_cart'),
    
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_URL)
   
   
   
    # path('add-to-cart/',views.add_to_cart,name='add-to-cart'),
    # path('cart/',views.cart_view,name='cart'),
    # path('delete-from-cart/',views.delete_item_from_cart,name='delete-from-cart'),
    # path('update-cart/',views.update_cart,name='update-cart'),
   
   

core/urls.py
from django.contrib import admin
from django.urls import path,include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("",include('product.urls')),
    path("user/",include('userauths.urls')),
    path("admin_side/",include('admin_side.urls')),
    path("category_manage/",include('category_manage.urls')),
    path("ad_product/",include('ad_product.urls')),
    path("account/",include('account.urls')),
    path("cart/",include('cart.urls')),
    path("order/",include('order.urls')),
    path("wallet/",include('wallet.urls')),
    path("brands/",include('brands.urls')),
    path("accounts/",include('django.contrib.auth.urls')),


    path('auth/', include('social_django.urls', namespace='social')),

]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)































# """
# URL configuration for core project.

# The `urlpatterns` list routes URLs to views. For more information please see:
#     https://docs.djangoproject.com/en/5.0/topics/http/urls/
# Examples:
# Function views
#     1. Add an import:  from my_app import views
#     2. Add a URL to urlpatterns:  path('', views.home, name='home')
# Class-based views
#     1. Add an import:  from other_app.views import Home
#     2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
# Including another URLconf
#     1. Import the include() function: from django.urls import include, path
#     2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
# """
# from django.contrib import admin
# from django.urls import path,include

# from django.conf import settings
# from django.conf.urls.static import static

# urlpatterns = [
#     path('admin/', admin.site.urls),
#     path("",include('product.urls')),
#     path("user/",include('userauths.urls')),
# ]

# urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
# urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

order/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'order'

urlpatterns = [
    path('order-manage-view', views.order_view, name="order_view"),
    path('place_order', views.place_order, name="place_order"),
    path('view-order_details', views.order_details, name="order_status"),
    path('download-invoice/<int:order_number>/', views.download_invoice, name='download_invoice'),
    path('view-order_listing/<int:id>', views.order_listing, name="order_listing"),
    path('view_order/<int:id>/', views.user_orders, name='view-orders'),
    path('cancel_order_req/<int:id>/', views.cancel_order_req, name="cancel_order_req"),
    path('view-cancel_order_request/<int:id>/', views.cancel_order, name="cancel_order"),
    path('return_order_req/<int:id>/', views.return_order_req, name="return_order_req"),
    path('view-return_order_request/<int:id>/', views.return_order, name="return_order"),

    path('view-admin_order', views.admin_order_view, name="admin_order_view"),
    path('admin/orders/filter/', views.filter_orders_by_date, name='filter_orders_by_date'),
    path('admin/orders/filter/pdf/', views.filter_orders_pdf, name='filter_orders_pdf'),
    path('admin_order_item_details/<int:id>/', views.admin_order_item_details, name="admin_order_item_details"),
    path('admin_order_item_view/<int:id>/', views.admin_order_item_view, name="admin_order_item_view"),
    path('admin_order_status/', views.admin_order_status, name="admin_order_status"), 
    path('admin_order_status_all/', views.admin_order_status_all, name="admin_order_status_all"), 
    
    path('user_details_views/<int:id>', views.user_details_views, name="user_details_views"),
    path('remove_coupon/', views.remove_coupon, name="remove_coupon"),
   
    path('payment/success',views.payment_success,name='success'),
    path('payment/failed',views.payment_failed,name='failed'),

    


    

]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_URL)

order/views.py
from django.conf import settings
import uuid
import razorpay
from django.http import Http404, JsonResponse
from django.shortcuts import  get_object_or_404, render, redirect
from django.contrib import messages
from product.models import User
from cart.models import Cart_Item,Cart, Coupon
from account.models import Address
from django.db.models import Q
from decimal import Decimal
from ad_product.models import ProductVariant
from order.models import Order,OrderItem,Payment
from account.models import UserProfile
from django.views.decorators.cache import cache_control
from django.shortcuts import get_object_or_404
from django.template.loader import render_to_string
from django.utils.html import strip_tags
from django.core.paginator import Paginator
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from wallet.models import *
from wallet.views import credit, easypay
from xhtml2pdf import pisa
from django.http import HttpResponse
from django.template.loader import get_template
from io import BytesIO
from django.utils.dateparse import parse_date


# Create your views here.
@login_required(login_url='userauths:sign-in')
def order_view(request):
    if request.user.is_superuser:
         return redirect('admin_side:dashboard')
    cart = Cart.objects.get(user = request.user)
    cart_items = Cart_Item.objects.filter(cart = cart.id)
    dis = 0
    for cart_item in cart_items:
        if cart_item.product.stock < cart_item.quantity:
            messages.warning(request, "The product doesn't have that many quantities available.")
            return redirect('cart:view_cart')
    
    

    myuser =request.user
    print(myuser)
    default_billing = None  
    default_shipping = None
    billing_address = None
    shipping_address = None
    try:
        default_shipping = Address.objects.filter(Q(is_shipping = True) & Q(is_default = True) & Q( user = request.user))
        default_billing = Address.objects.filter(Q(is_billing = True) & Q(is_default = True) & Q( user = request.user))
        billing_address = Address.objects.filter(Q(is_billing = True) & Q(is_default = False) & Q( user = request.user))
        shipping_address = Address.objects.filter(Q(is_shipping = True) & Q(is_default = False) & Q( user = request.user))
        
    except Exception as e:
        print(f'exception = {e}')
    context = {
        'cart' : cart,  
        'dis' : dis,  
        'cart_items': cart_items,
        'default_billing' :default_billing if default_billing else None ,
        'default_shipping' :default_shipping if default_shipping else None,
        'billing_address':billing_address if billing_address else None,
        'shipping_address':shipping_address if shipping_address else None,
    }
    return render(request, 'user/checkout.html',context)


def remove_coupon(request):
    last_order = Order.objects.latest('order_time')
    cart = Cart.objects.get(user = request.user)
    code = cart.coupon
    coupon = Coupon.objects.filter(code=code, is_active=True).first()
    cart_item = Cart_Item.objects.filter(cart = cart)
    print(coupon)
    if coupon:
        discount = cart.total * coupon.discount /100
        cart.coupon = coupon

        if discount > coupon.max_discount_amount:
            discount = coupon.max_discount_amount
        cart.total = cart.sub_total + cart.shipping
        
        print(f'discount={discount}')

        del request.session['coupon']
        cart.coupon = None

        cart.save()
        messages.success(request,'Coupon removed')
        return redirect("order:order_view")
    else:
        messages.warning(request, "Coupon does'nt exist")
        return redirect("order:order_view")



@login_required(login_url='userauths:sign-in')
def place_order(request):
    if request.user.is_superuser:
         return redirect('admin_side:dashboard')
    context = {} 

    if request.method == 'POST':    

        if 'cod' in request.POST:
            shipping_address_id = request.POST.get('shipping_add')
            billing_address_id = request.POST.get('billing_add')
            

            try:
                shipping = Address.objects.get(id=shipping_address_id)
                billing = Address.objects.get(id=billing_address_id)
            except (Address.DoesNotExist, ValueError):
                messages.warning(request, 'No address selected')
                print('not working')
                return redirect('order:order_view')
            
            shipping_full_address = shipping.FullAddress()
            billing_full_address = billing.FullAddress()
            print(shipping_full_address)
            print(billing_full_address)

            cart = Cart.objects.get(user = request.user)
            cart_item = Cart_Item.objects.filter(cart = cart)

            if cart_item.exists():
                payment_maker = Payment.objects.create(
                user=request.user,
                payment_method = "COD",
                payment_status = 'PENDING',
                amount_paid = cart.total,
                )
                try:
                    new_order =Order.objects.create(
                    user=request.user,
                    payment_details = payment_maker,
                    shipping_address = shipping_full_address,
                    billing_address = billing_full_address,
                    order_total = cart.total ,
                    order_subtotal = cart.sub_total,
                    order_shipping = cart.shipping,
                    )
                    if 'coupon' in request.session:
                        coupon = request.session.get('coupon')
                        coupon = Coupon.objects.get(pk = coupon)
                        new_order.order_coupon = coupon
                        new_order.save()
                        coupon_discount = cart.total * coupon.discount /100
                        if coupon_discount > coupon.max_discount_amount:
                            coupon_discount = coupon.max_discount_amount
                    else:
                        coupon_discount = 0
                    request.session['new_order'] = new_order.pk
                    cart.save()

                except Exception as e:
                    print(f' the error {e}')

            for cart_item in cart_item:
                product = ProductVariant.objects.get(id=cart_item.product.id)
                uu_order_id = int(uuid.uuid4().hex[:8],16)
                uu_order_id = f"#{uu_order_id}"
                total_product_price = cart_item.product.sale_price * cart_item.quantity

                order_item, _ = OrderItem.objects.get_or_create(
                    user=request.user, 
                    order_product=product,
                    order_item_id = uu_order_id,
                    quantity=cart_item.quantity, 
                    product_price=total_product_price, 
                    payment_details=payment_maker,
                    order = new_order,
                    order_status = 'PLACED',
                    )
                
                product.stock -= cart_item.quantity
                product.save()
                order_item.save()
                cart_item.delete()

            new_order = None  # Default value if new_order is not defined
            order_items = []
            last_order = Order.objects.latest('order_time')
                    
            if last_order:
                last_order_id = last_order.order_number
            else:
                last_order_id = None 
            new_order_id = request.session.get('new_order')
            order_id = new_order_id
            if order_id:
                new_order = Order.objects.get(pk=order_id)
                order_items = OrderItem.objects.filter(order=new_order)
            else:
                new_order = Order.objects.get(pk=last_order_id)
                order_items = OrderItem.objects.filter(order=new_order)
            context = {
            'new_order': new_order,
            'order_items': order_items,
            'coupon_discount': coupon_discount
            }
            
            return render(request, 'user/order_summary.html', context)
        
        
            
        
        elif 'coupon_submit' in request.POST:
            last_order = Order.objects.latest('order_time')
            code = request.POST.get("user_coupon")
            coupon = Coupon.objects.filter(code=code, is_active=True).first()
            cart = Cart.objects.get(user = request.user)
            cart_item = Cart_Item.objects.filter(cart = cart)
            
            if coupon:
                if cart.coupon and coupon == cart.coupon:
                    messages.warning(request, 'Coupon already applied')
                    return redirect("order:order_view")
                else:

                    discount = cart.total * coupon.discount /100
                    cart.coupon = coupon

                    if discount > coupon.max_discount_amount:
                        discount = coupon.max_discount_amount
                    cart.total = cart.sub_total + cart.shipping
                    cart.total -= discount
                    print(f'discount={discount}')

                    request.session['coupon'] = coupon.pk

                    cart.save()
                    messages.success(request,'Coupon applied')
                    return redirect("order:order_view")
            else:
                messages.warning(request, "Coupon does'nt exist")
                return redirect("order:order_view")
            

        elif 'order_pay' in request.POST:
            shipping_address_id = request.POST.get('shipping_add')
            billing_address_id = request.POST.get('billing_add')
            

            try:
                shipping = Address.objects.get(id=shipping_address_id)
                billing = Address.objects.get(id=billing_address_id)
            except (Address.DoesNotExist, ValueError):

templates/user/order/invoice.html
<!-- templates/invoice.html -->
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Invoice</title>
    <style>
        body { font-family: Arial, sans-serif; }
        .invoice-box {
            max-width: 800px;
            margin: auto;
            padding: 30px;
            border: 1px solid #eee;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.15);
            font-size: 16px;
            line-height: 24px;
            color: #555;
        }
        .invoice-box table {
            width: 100%;
            line-height: inherit;
            text-align: left;
        }
        .invoice-box table td {
            padding: 5px;
            vertical-align: top;
        }
        .invoice-box table tr td:nth-child(2) {
            text-align: right;
        }
        .invoice-box table tr.top table td {
            padding-bottom: 20px;
        }
        .invoice-box table tr.information table td {
            padding-bottom: 40px;
        }
        .invoice-box table tr.heading td {
            background: #eee;
            border-bottom: 1px solid #ddd;
            font-weight: bold;
        }
        .invoice-box table tr.details td {
            padding-bottom: 20px;
        }
        .invoice-box table tr.item td{
            border-bottom: 1px solid #eee;
        }
        .invoice-box table tr.item.last td {
            border-bottom: none;
        }
        .invoice-box table tr.total td:nth-child(2) {
            border-top: 2px solid #eee;
            font-weight: bold;
        }
    </style>
</head>
<body>
    <div class="invoice-box">
        <table cellpadding="0" cellspacing="0">
            <tr class="top">
                <td colspan="2">
                    <table>
                        <tr>
                            <td class="title">
                                <h2>Invoice</h2>
                            </td>
                            
                            <td>
                                Order #: {{ order.order_number }}<br>
                                Created: {{ order.order_time }}<br>
                                Due: {{ order.order_time }}
                            </td>
                        </tr>
                    </table>
                </td>
            </tr>
            
            <tr class="information">
                <td colspan="2">
                    <table>
                        <tr>
                            <td>
                                Shipping Address:<br>
                                {{ shipping }}
                            </td>
                            
                            <td>
                                Billing Address:<br>
                                {{ billing }}
                            </td>
                        </tr>
                    </table>
                </td>
            </tr>
            
            <tr class="heading">
              <td colspan="2">
                <table>
                    <tr>
                        <td>
                          Payment Method
                            
                        </td>
                        
                        <td>
                          Amount
                        </td>
                    </tr>
                </table>
              </td>
            
            
            <tr class="details" colspan='2'>
              <td colspan="2">
                <table>
                    <tr>
                        <td>
                          {{ order.payment_details.payment_method }}                            
                        </td>
                        
                        <td>
                          {{ order.order_total }}
                        </td>
                    </tr>
                </table>
              </td>
            </tr>
            
            <tr class="heading" colspan='2'>
              <td colspan="2">
                <table>
                    <tr>
                        <td>
                          Item                          
                        </td>
                        
                        <td>
                          Price
                        </td>
                    </tr>
                </table>
              </td>
                
            </tr>
            
            {% for item in order_item %}
            <tr class="item">
              <td colspan="2">
                <table>
                    <tr>
                        <td>
                          {{ item.order_product.product }} x {{item.quantity}} nos.
                        </td>
                        
                        <td>
                          {{ item.product_price }}
                        </td>
                    </tr>
                </table>
              </td>
                
            </tr>
            {% endfor %}
            <tr class="total heading">
              <td>Total:</td>
              
              <td>
                  {{ total }}
              </td>
            </tr>
            <tr class="total">
              <td>Discount:</td>
              
              <td>
                {% if discount <= 0 %}
                    0
                {% else %}
                  {{ discount }}
                {% endif %}
              </td>
            </tr>
            <tr class="total heading">
                <td>Grand total:</td>
                
                <td>
                    {{ order.order_total }}
                </td>
            </tr>
        </table>
    </div>
</body>
</html>

templates/user/order/order_cancel_reason.html
{% extends "partials/base.html" %} 
{% block title %}Cart{% endblock title %} 
{%block content %}
{% load custom_filters %}
{% load static %}
    <div class="card" style="width: 37rem; margin-top:10rem; margin-left:27rem;">
        <div class="card-body">
            <h3>Order Cancellation Request</h3>
            <br>
            <div class="card card-2">
              <div class="card-body">
                  <div class="media">
                      <!-- Display the image on the left -->
                      <div class="align-self-center">
                          <img width="auto" height="100" style="border-radius: 30px;"  src="{{ item.order_product.variantimage_set.first.images.url }}" />
                      </div>
                      <div class="media-body ml-3">
                          <!-- Display product details on the right -->
                          <div class="row">
                              <div class="col">
                                  <h4>{{ item.order_product.product }}</h4>
                              </div>
                          </div>
                          <div class="row">
                              <div class="col">
                                  <small>{{ item.order_product.color }}</small>
                              </div>
                          </div>
                          <div class="row">
                              <div class="col">
                                  <small>Qty: {{ item.quantity }}</small>
                              </div>
                          </div>
                          <div class="row">
                              <div class="col">
                                  <h6 class="mb-0">Price: &#8377; {{ item.product_price|mul:item.quantity }}</h6>
                              </div>
                          </div>
                      </div>
                  </div>
              </div>
          </div>
          
            <p>Welcome to the Order Cancellation Request page. If you've changed your mind or encountered any issues, you can confirm the cancellation of your order here. Please review the details of your order below and proceed with the cancellation if you wish to do so. If you have any questions, feel free to contact our customer support for assistance. Thank you for your understanding.</p>
            <form action="{% url 'order:cancel_order' item.id %}" method="POST">
                {% csrf_token %}
                <p>Reason for cancellation</p>
                <input type="text" name="reason" required>
                <br>
                <br>
                <div>
                  <button class="btn button" type="submit"><a>Cancel Order</a></button>
                <a href="" class="btn button">Change of mind ?</a>
                </div>
            </form>
        </div>
    </div>
    <script>
        $(document).ready(function (){
            $('#back_me').on("click", function (){
                history.back();
            })
        })
    </script>
    {% endblock content %}

templates/user/order/order_return_reason.html
{% extends "partials/base.html" %} 
{% block title %}Cart{% endblock title %} 
{%block content %}
{% load custom_filters %}
{% load static %}
    <div class="card" style="width: 37rem; margin-top:10rem; margin-left:27rem;">
        <div class="card-body">
            <h3>Order Return Request</h3>
            <br>
            <div class="card card-2">
              <div class="card-body">
                  <div class="media">
                      <!-- Display the image on the left -->
                      <div class="align-self-center">
                          <img width="auto" height="100" style="border-radius: 30px;"  src="{{ item.order_product.variantimage_set.first.images.url }}" />
                      </div>
                      <div class="media-body ml-3">
                          <!-- Display product details on the right -->
                          <div class="row">
                              <div class="col">
                                  <h4>{{ item.order_product.product }}</h4>
                              </div>
                          </div>
                          <div class="row">
                              <div class="col">
                                  <small>{{ item.order_product.color }}</small>
                              </div>
                          </div>
                          <div class="row">
                              <div class="col">
                                  <small>Qty: {{ item.quantity }}</small>
                              </div>
                          </div>
                          <div class="row">
                              <div class="col">
                                  <h6 class="mb-0">Price: &#8377; {{ item.product_price|mul:item.quantity }}</h6>
                              </div>
                          </div>
                      </div>
                  </div>
              </div>
          </div>
          
            <p>Welcome to the Order Return Request page. If you've changed your mind or encountered any issues, you can confirm the Return of your order here. Please review the details of your order below and proceed with the Return if you wish to do so. If you have any questions, feel free to contact our customer support for assistance. Thank you for your understanding.</p>
            <form action="{% url 'order:return_order' item.id %}" method="POST">
                {% csrf_token %}
                <p>Reason for cancellation</p>
                <input type="text" name="reason" required>
                <br>
                <br>
                <div>
                  <button class="btn button" type="submit"><a>Return Order</a></button>
                <a href="" class="btn button">Change of mind ?</a>
                </div>
            </form>
        </div>
    </div>
    <script>
        $(document).ready(function (){
            $('#back_me').on("click", function (){
                history.back();
            })
        })
    </script>
    {% endblock content %}