cart/urls.py
from . import views
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

app_name='cart'

urlpatterns = [
    path('cart-view',views.view_cart,name='view_cart'),
    path('cart-add/<int:id>/',views.add_cart,name='add_cart'),
    path('cart-add/',views.add_cart,name='add_cart'),
    path('cart-delete/<int:id>/',views.delete_cart,name='delete_cart'),
    path('plus-item/',views.item_plus,name='plus_item'),
    path('minus-item/',views.item_minus,name='minus_item'),
    path('clear_cart/',views.clear_cart,name='clear_cart'),
    
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_URL)
   
   
   
    # path('add-to-cart/',views.add_to_cart,name='add-to-cart'),
    # path('cart/',views.cart_view,name='cart'),
    # path('delete-from-cart/',views.delete_item_from_cart,name='delete-from-cart'),
    # path('update-cart/',views.update_cart,name='update-cart'),
   
   

core/urls.py
from django.contrib import admin
from django.urls import path,include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("",include('product.urls')),
    path("user/",include('userauths.urls')),
    path("admin_side/",include('admin_side.urls')),
    path("category_manage/",include('category_manage.urls')),
    path("ad_product/",include('ad_product.urls')),
    path("account/",include('account.urls')),
    path("cart/",include('cart.urls')),
    path("order/",include('order.urls')),
    path("wallet/",include('wallet.urls')),
    path("brands/",include('brands.urls')),
    path("accounts/",include('django.contrib.auth.urls')),


    path('auth/', include('social_django.urls', namespace='social')),

]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)































# """
# URL configuration for core project.

# The `urlpatterns` list routes URLs to views. For more information please see:
#     https://docs.djangoproject.com/en/5.0/topics/http/urls/
# Examples:
# Function views
#     1. Add an import:  from my_app import views
#     2. Add a URL to urlpatterns:  path('', views.home, name='home')
# Class-based views
#     1. Add an import:  from other_app.views import Home
#     2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
# Including another URLconf
#     1. Import the include() function: from django.urls import include, path
#     2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
# """
# from django.contrib import admin
# from django.urls import path,include

# from django.conf import settings
# from django.conf.urls.static import static

# urlpatterns = [
#     path('admin/', admin.site.urls),
#     path("",include('product.urls')),
#     path("user/",include('userauths.urls')),
# ]

# urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
# urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

product/urls.py
from django.urls import path, include 
from product.views import *
from django.conf import settings
from django.conf.urls.static import static

app_name = 'product'

urlpatterns = [
    path('',index, name='index'),
    path('products/',product_list_view, name='product-list'),
    path("products/<int:pid>/<int:cate_id>/", product_detail_view, name="product-detail"),
    path("category/", category_list_view, name="category-list"),
    path("category/<id>/", category_product_list, name="category-product-list"),
    path("brand/", brand_list_view, name="brand-list"),
    path("brand/<id>/", brand_product_list, name="brand-product-list"),
    path("search/", search_view, name="search"),
    path("varnts/<int:pid>/<int:avid>/", varnts, name="varnts"),

    ### sort and filter
    path("add-review/<int:id>/", ajax_add_review, name="add-review"),
    path("filter-product/", filter_product, name="filter-product"),

    ###  wishlist
    path('add-to-wishlist/<int:prid>/<int:cid>/', add_wishlist, name='add_wishlist'),
    path('view-from-wishlist/', view_wishlist, name='wishlist'),
    path('delete-from-wishlist/<int:prid>/', delete_wishlist, name='delete_wishlist'),



]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_URL)

cart/models.py
from django.db import models
from product.models import User
from ad_product.models import ProductVariant
from django.utils import timezone


class Coupon(models.Model):
    code = models.CharField(max_length=10, unique=True)
    discount = models.DecimalField(decimal_places=2, max_digits=8)
    max_discount_amount = models.DecimalField(decimal_places=2, max_digits=8, blank=True, null=True, default=10000)
    valid_from = models.DateTimeField(auto_now_add=True)
    valid_to = models.DateTimeField()
    is_active = models.BooleanField(default=True)

    def __str__(self):
        return f"{self.code}"
    
    @property
    def discount_percentage(self):
        return (self.discount * 100) / 100
    
    def coupon_name(self):
        return f"{self.code}"
    
    def save(self, *args, **kwargs):
        if self.valid_to and self.valid_to < timezone.now():
            self.is_active = False
        super().save(*args, **kwargs)
    
class Cart(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    coupon = models.ForeignKey(Coupon, on_delete=models.SET_NULL, blank=True, null = True)
    total = models.DecimalField(decimal_places=2, max_digits=10,default=0, null=True)
    sub_total = models.DecimalField(decimal_places=2, max_digits=10,default=0, null=True)
    shipping = models.DecimalField(decimal_places=2, max_digits=10,default=0, null=True)
    created_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'{self.user}-cart'

    

class Cart_Item(models.Model):
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE)
    product = models.ForeignKey(ProductVariant, on_delete=models.SET_NULL, null=True)
    quantity = models.IntegerField(default= 1)
    is_active = models.BooleanField(default=True)

    def __str__(self):
        return f"{self.cart}-item - {self.product}"
    
    














































# from django.db import models
# from product.models import User
# from ad_product.models import ProductVariant
    

    
# class Cart(models.Model):
#     user = models.ForeignKey(User, on_delete=models.CASCADE)
#     total = models.DecimalField(decimal_places=2, max_digits=10,default=0, null=True)
#     sub_total = models.DecimalField(decimal_places=2, max_digits=10,default=0, null=True)
#     shipping = models.DecimalField(decimal_places=2, max_digits=10,default=0, null=True)
#     created_date = models.DateTimeField(auto_now_add=True)

#     def __str__(self):
#         return f'{self.user}-cart'

    

# class Cart_Item(models.Model):
#     cart = models.ForeignKey(Cart, on_delete=models.CASCADE)
#     product = models.ForeignKey(ProductVariant, on_delete=models.SET_NULL, null=True)
#     quantity = models.IntegerField(default= 1)
#     is_active = models.BooleanField(default=True)

#     def __str__(self):
#         return f"{self.cart}-item - {self.product}"
    
    

cart/views.py
# from datetime import datetime as dt
from django.shortcuts import render, redirect, get_object_or_404
# from django.views.decorators.cache import cache_control
from django.contrib import messages
from cart.models import Cart_Item,Cart
from django.db.models import Q
from ad_product.models import ProductVariant
from decimal import Decimal
from django.http import JsonResponse
from django.template.loader import render_to_string



def view_cart(request):
    if not request.user.is_authenticated:
        if request.user.is_superuser:
            return redirect('admin_side:login')
        messages.info(request,'Please log in to view cart')
        return redirect('userauths:sign-in')

    cart, check_cart = Cart.objects.get_or_create(user=request.user)
    cart_items = Cart_Item.objects.filter(cart=cart).order_by('id')
 
    subtotal = sum(item.product.sale_price * item.quantity for item in cart_items)
    shipping = 0
    total = Decimal(subtotal)
    count = Cart_Item.objects.all().count()

    # checking if the user can get free delivery
    if subtotal < 200000:
        shipping = (subtotal * Decimal('0.1')) / 100
        total += shipping  # Include shipping in the total

    if request.method == 'POST':
        if total != 0:
            cart.sub_total = subtotal
            cart.total = total
            cart.shipping = shipping
            cart.save()
            return redirect('cart:view_cart')

    # Check if the cart is empty and update the Cart model
    if not cart_items:
        cart.total = None
        cart.sub_total = None
        cart.shipping = None
        cart.save()
        messages.info(request,'Cart is Running on Low')

        

        
    context = {
        'itemtotlal' : subtotal,
        'item': cart_items,  # Renamed 'item' to 'items' for clarity
        'pro_subtotal': cart.sub_total if cart.sub_total else subtotal,
        'shipping': cart.shipping if cart.shipping else shipping,
        'total': cart.total if cart.total else total,
        'cart': Cart.objects.filter(user=request.user),
        'count':count,
    }
    return render(request, 'user/cart.html', context)







def add_cart(request, id=None):
    if not request.user.is_authenticated:
        return redirect('userauths:sign-in')

    product_quantity = int(request.POST.get('prod_qty')) if request.POST.get('prod_qty') else 1
    product_id = int(request.POST.get('prod_id')) if request.POST.get('prod_id') else id
    product = get_object_or_404(ProductVariant, id = product_id)
    cart, check_cart = Cart.objects.get_or_create(user=request.user)
    try:
        item_check = Cart_Item.objects.get(cart=cart, product=product)
        print(f'helooo{item_check}')
        if product_quantity > product.stock :
            messages.warning(request, "can't add that many due to stock insufficient")
            return redirect('cart:view_cart')
        elif item_check.quantity + product_quantity > product.stock:
             
            messages.warning(request, 'cant add that many due to stock insufficient')
            return redirect('cart:view_cart')
        else:
            
            item_check.quantity += product_quantity if product_quantity else 1
            item_check.save()
            cart_item = Cart_Item.objects.filter(cart = cart)
            subtotal = sum(item.product.sale_price * item.quantity for item in cart_item)
            shipping = 0
            if subtotal <200000:
                shipping = (subtotal * Decimal('0.1')) / 100
            cart.sub_total = subtotal
            cart.total = subtotal if subtotal else 0
            cart.total += shipping if shipping else 0
            cart.shipping = shipping if shipping else 0
            cart.save()
            messages.success(request, 'The product is in the cart')
            return redirect("cart:view_cart")
    except Cart_Item.DoesNotExist:
        Cart_Item.objects.create(cart=cart, product=product, quantity=product_quantity if product_quantity else 1)
        cart_item = Cart_Item.objects.filter(cart = cart)
        subtotal = sum(item.product.sale_price * item.quantity for item in cart_item)
        shipping = 0
        if subtotal <200000:
            shipping = (subtotal * Decimal('0.1')) / 100
        cart.sub_total = subtotal
        cart.total = subtotal if subtotal else 0
        cart.total += shipping if shipping else 0
        cart.shipping = shipping if shipping else 0
        cart.save()  
        messages.success(request, 'The item has been added to the cart')

        return redirect("cart:view_cart")





def delete_cart(request,id):
    cart_item = Cart_Item.objects.filter(id = id)
    if cart_item:
        cart_item.delete()
        messages.info(request, f"the item has been deleted from cart")
    myCart =Cart.objects.get(user = request.user)
    del_cart = Cart_Item.objects.filter(cart =myCart)
    subtotal = sum(item.product.sale_price * item.quantity for item in del_cart) 
    product_per_price = subtotal
    shipping = Decimal(0)
    if subtotal < 200000:
        shipping = (subtotal * Decimal('0.1'))/100
    myCart.sub_total = product_per_price if product_per_price else 0
    myCart.total = subtotal
    myCart.total += shipping if shipping else 0
    myCart.shipping = shipping if shipping else 0
    myCart.save()
    if del_cart is None:
        myCart.total = None
        myCart.sub_total = None
        myCart.shipping = None
    return redirect('cart:view_cart')   

def item_plus(request):
   
    if request.headers.get('x-requested-with') == 'XMLHttpRequest' and request.method == 'POST':
        try:
            cart = get_object_or_404(Cart, user = request.user)
            id = request.POST.get('cart_id')
            cart_item = get_object_or_404(Cart_Item, cart = cart, id = id)
            if cart_item.quantity < cart_item.product.stock:
                cart_item.quantity += 1
                cart_item.save()
            subtotal = Decimal(0)   
            cart_item = Cart_Item.objects.filter(cart = cart)
            subtotal = sum(item.product.sale_price * item.quantity for item in cart_item) 
            product_per_price = subtotal
            shipping = Decimal(0)
            if subtotal < 200000:
                shipping = (subtotal * Decimal('0.1'))/100
        
            cart.sub_total = product_per_price if product_per_price else 0
            cart.total = subtotal
            cart.total += shipping if shipping else 0
            cart.shipping = shipping if shipping else 0
            cart.save()
            quantity = [{'id': item.id, 'quantity': item.quantity} for item in cart_item]
            data = {
                'quantity' : quantity,
                'subtotal' : f'₹ {product_per_price: .2f}',
                'shipping': f'₹ {shipping:.2f}' if shipping else 'Free Shipping',
                'total': f'₹ {cart.total:.2f}',
            }
            return JsonResponse(data)
        except Exception as e:
            # Log the exception for debugging purposes
            print(f"An error occurred: {str(e)}")
            messages.info(request, 'Cant add more product quantity than its products stock')
    # return JsonResponse({'error': 'Invalid request'}, status=400)
      

def item_minus(request):
   
    if request.headers.get('x-requested-with') == 'XMLHttpRequest' and request.method == 'POST':
        try:
            cart = get_object_or_404(Cart, user = request.user)
            id = request.POST.get('cart_id')
            cart_item = get_object_or_404(Cart_Item, cart = cart, id = id)
            print(cart_item.product.stock)
            print(cart_item.quantity)
            if cart_item.quantity > 1 and cart_item.quantity <= cart_item.product.stock:
                cart_item.quantity -= 1
                cart_item.save()


            subtotal = Decimal(0)   
            cart_item = Cart_Item.objects.filter(cart = cart)
            subtotal = sum(item.product.sale_price * item.quantity for item in cart_item)   
            cart.sub_total = subtotal
            product_per_price = subtotal
            shipping = Decimal(0)
            if subtotal < 200000:
                shipping = (subtotal * Decimal('0.1'))/100
            cart.sub_total = product_per_price if product_per_price else 0
            cart.total = subtotal
            cart.total += shipping if shipping else 0
            cart.shipping = shipping if shipping else 0
            cart.save()
            quantity = [{'id': item.id, 'quantity': item.quantity} for item in cart_item]
            data = {
                'quantity' : quantity,
                'subtotal' : f'₹ {product_per_price: .2f}',
                'shipping': f'₹ {shipping:.2f}' if shipping else 'Free Shipping',
                'total': f'₹ {cart.total:.2f}',
            }
            return JsonResponse(data)
        except Exception as e:
            # Log the exception for debugging purposes
            print(f"An error occurred: {str(e)}")
            return JsonResponse({'error': 'An error occurred'}, status=500)
        
    return JsonResponse({'error': 'Invalid request'}, status=400)


def clear_cart(request):
    cart = get_object_or_404(Cart, user = request.user)
    cart_item = Cart_Item.objects.filter(cart=cart)
    cart_item.delete()
    cart.save()
    messages.info(request,'all the cart items have been deleted')
    return redirect('cart:view_cart')

templates/user/order_summary.html
{% extends "partials/base.html" %} 
{%block content %}
{% load static %} 
{% load custom_filters %}



<main>
  <div class="container w-75">
    <div class="row">
      <div class="my-5">
        <p class="h3">Order Summary</p>
      </div>
      <table class="table table-striped border">
        <thead>
          <tr>
            <th  scope="col"  class="w-10" ></th>
            <th scope="col" colspan="2" class="text-center" style="width: 5vw;">Product name</th>
            <th scope="col" colspan="2" class="text-center" style="width: 5vw;">Price</th>
            <th scope="col" colspan="2" class="text-center" style="width: 5vw;">Quantity</th>
            <th scope="col" colspan="2" class="text-end" style="width: 5vw;padding-right: 2vw;">Total</th>
          </tr>
        </thead>
        <tbody>
          {% for item in order_items %}
            <tr class="border">
              <th scope="row" class="w-10">
                <img src="{{ item.order_product.variantimage_set.first.images.url}}" class="img-fluid rounded-3" style="width: 120px;" alt="Book" />
              </th>
              <td colspan="2" class="text-center">{{ item.order_product.product }}
                <br>{{item.order_product.color}}
              </td>
              <td colspan="2" class="text-center">₹ {{ item.order_product.sale_price }}</td>
              <td colspan="2" class="text-center">{{ item.quantity }}</td>
              <td colspan="2" class="text-end" style="padding-right: 2vw;">₹ {{ item.order_product.sale_price|mul:item.quantity }}</td>
            </tr>
          {% endfor %}

          <tr class="border">
            <th colspan="5" class="text-center">Shipping</th>
            <td colspan="5" class="text-end" style="padding-right: 1vw;">₹ {{ new_order.order_shipping }}</td>
          </tr>
          <tr class="border">
            <th colspan="5" class="text-center">Discount</th>
            <td colspan="5" class="text-end" style="padding-right: 1vw;">₹ {{ coupon_discount }}</td>
          </tr>
          <tr class="border">
            <th colspan="5" class="text-center">Grand Total</th>
            <td colspan="5" class="text-end" style="padding-right: 2vw;">₹ {{ new_order.order_total }}</td>
          </tr>
          <tr class="">
            <td colspan="5" class="border">
              <table class="table mb-0">
                <tr>
                  <td colspan="5"><center>Delivery Address</center></td>
                </tr>
                <tr>
                  <td colspan="5" style="padding-left: 4vw;">
                    {{ new_order.shipping_address|upper}}
                  </td>
                </tr>
              </table>
            </td>
            <td colspan="5" class="border">
              <table class="table mb-">
                <tr>
                  <td colspan="5" class="text-center align-top">
                  
                    {{new_order.payment_details.payment_method}}
                    
                  </td>
                </tr>
                <tr>
                  <td class="text-center">
                  {% if new_order.payment_details.payment_method != 'COD' %}
                  
                    <button id="rzp-button1" class="bg-info border-0 rounded-2 py-2 px-3 text-light">Pay with Razorpay</button>
                  {% endif %}
                  </td>
                </tr>
                
              </table>
            </td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
</main>


{% endblock content %} 
{% block payment-gateway %}

<script src="https://checkout.razorpay.com/v1/checkout.js"></script>
<script>
var options = {
    "key": "rzp_test_yrlRK4RRuxfuVA", // Enter the Key ID generated from the Dashboard
    "amount": "{{payment.amount}}",  // Amount is in currency subunits. Default currency is INR. Hence, 50000 refers to 50000 paise
    "currency": "INR",
    "name": "Acme Corp", //your business name
    "description": "Test Transaction",
    "image": "https://example.com/your_logo",
    "order_id": "{{payment.id}}", //This is a sample Order ID. Pass the `id` obtained in the response of Step 1
    "handler": function (response){
      window.location.href = `{{success}}?payment_id=${response.razorpay_payment_id}&razorpay_order_id=${response.razorpay_order_id}&payment_sign=${response.razorpay_signature}`
        {% comment %} alert(response.razorpay_payment_id);
        alert(response.razorpay_order_id);
        alert(response.razorpay_signature) {% endcomment %}
    },
    "prefill": { //We recommend using the prefill parameter to auto-fill customer's contact information, especially their phone number
        "name": "Gaurav Kumar", //your customer's name
        "email": "gaurav.kumar@example.com", 
        "contact": "9000090000"  //Provide the customer's phone number for better conversion rates 
    },
    "notes": {
        "address": "Razorpay Corporate Office"
    },
    "theme": {
        "color": "#3399cc"
    }
};
var rzp1 = new Razorpay(options);
rzp1.on('payment.failed', function (response){
  window.location.href=`{{failed}}?error_code=${response.error.code}&error_description=${response.error.description}&error_reason=${response.error.reason}&error_payment_id=${response.error.metadata.payment_id}&error_order_id=${response.error.metadata.order_id}&method=COD`
        {% comment %} alert(response.error.code);
        alert(response.error.description);
        alert(response.error.source);
        alert(response.error.step);
        alert(response.error.reason);
        alert(response.error.metadata.order_id);
        alert(response.error.metadata.payment_id); {% endcomment %}
});
document.getElementById('rzp-button1').onclick = function(e){
    rzp1.open();
    e.preventDefault();
}
</script>

{% endblock payment-gateway %}

templates/user/wishlist.html
{% extends "partials/base.html" %} 
{% block title %}Wishlist{% endblock title %} 
{%block content %}
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">


<div class="page-header breadcrumb-wrap">
    <div class="container">
        <div class="breadcrumb">
            <a href="{% url "product:index" %}" rel="nofollow">Home</a>
            <span></span> Wishlist
        </div>
    </div>
</div>  


<section class="mt-50 mb-50">
    <div class="container">
        <div class="row">
            <div class="col-12">
                <div class="table-responsive">
                    <table class="table shopping-summery text-center">
                        <thead>
                            <tr class="main-heading">
                                <th scope="col" colspan="2">Product</th>
                                <th scope="col">Price</th>
                                <th scope="col">Stock Status</th>
                                <th scope="col">Action</th>
                                <th scope="col">Remove</th>
                            </tr>
                        </thead>
                        <tbody>
                         {% if items|default:""|length > 0 %} 
                         {% for item in items %}
                            <tr>
                                <td class="image product-thumbnail"><img height="90px" width="90px"  src='{{item.variantimage_set.first.images.url}}' alt="#"></td>
                                <td class="product-des product-name">
                                    <h5 class="product-name"><a href="{% url "product:product-detail" item.id item.product.product_catg.id %}">{{item.product}}</a></h5>
                                    <p class="font-xs">{{item.color}}
                                    </p>
                                </td>
                                <td class="price" data-title="Price"><span>{{item.sale_price}}</span></td>
                                <td class="text-center" data-title="Stock">
                                    <span class="color3 font-weight-bold">{{item.stock}}</span>
                                </td>
                                <td class="text-right" data-title="Cart">
                                    {% if item.stock < 1 %}
                                    <img width="64" height="64" src="https://img.icons8.com/external-victoruler-linear-colour-victoruler/64/external-out-of-stock-logistics-victoruler-linear-colour-victoruler.png" alt="external-out-of-stock-logistics-victoruler-linear-colour-victoruler"/>
                                    {% else %}
                                  
                                  <a href="{% url 'cart:add_cart' id=item.id %}"><button class="btn btn-sm" aria-label="Add To Cart" data-index="{{ p.id }}" id="add-to-cart-btn"><i class="fi-rs-shopping-bag mr-5"></i>Add to cart</button></a>  
                                    {% endif %}
                                </td>
                                <td class="action" data-title="Remove"><a href="{% url "product:delete_wishlist" prid=item.id%}"><i class="fi-rs-trash"></i></a></td>
                            </tr>
                            {% endfor %}
                            {% else %}
                            <tr>
                                
                                
                                <td><img width="80" height="80" src="https://img.icons8.com/dotty/80/nothing-found.png" alt="nothing-found"/></td>
                                <td><img width="80" height="80" src="https://img.icons8.com/dotty/80/nothing-found.png" alt="nothing-found"/></td>
                                <td><img width="80" height="80" src="https://img.icons8.com/dotty/80/nothing-found.png" alt="nothing-found"/></td>
                                <td><img width="80" height="80" src="https://img.icons8.com/dotty/80/nothing-found.png" alt="nothing-found"/></td>
                                <td><img width="80" height="80" src="https://img.icons8.com/dotty/80/nothing-found.png" alt="nothing-found"/></td>
                                <td><img width="80" height="80" src="https://img.icons8.com/dotty/80/nothing-found.png" alt="nothing-found"/></td>
                            </tr>
                            {% endif %}  
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</section>



{% endblock content %}